# baseURL = 'https://takesxisximada.github.io/OpenEndedCodebook/'
baseURL = 'http://http://192.168.207.167:1313'
languageCode = 'ja'
title = 'Openended Evolution - Pythonで実装する進化するAI'
publishDir = '../public'
contentDir = "../appendix/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokai'
    tabWidth = 4
